### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by joshtronic** [icholy/holidayapi#1]
Not sure if it was you or not that reached out to me, but wanted to drop a note to say thank you.

Admittedly, Golang isn't a language I have much experience with, so my wrapper (being my first or second Golang project ever) did in fact suck.

I'm working on some improvements to our documentation page this week, so expect to see this listed there soon :)

**Comment by icholy** [comment]
Somehow I didn't see this until now. I appreciate you listing it in the api docs :)
